### PR TITLE
Remove TODOs from workflows.

### PR DESCRIPTION
**Pull request by mgr0dzicki**
Of course I still have to make corresponding changes in https://github.com/mgr0dzicki/cargo-semver-action-ref-slice.

But first, I wanted to ask to be 100% sure. @obi1kenobi, since `v2` using baseline choosing logic of `cargo-semver-checks` is merged into main, we can safely change the version in tests from `1.2.2` to `1.2.1`, can't we?

### CODE REVIEW

**Comment by obi1kenobi** [comment]
I'm honestly not sure either. I don't remember what that TODO was for, and it doesn't say _which bad thing_ happens if the version were to change inappropriately. This is why writing detailed TODOs is important while you still have all the details in mind :)

If you think it's safe, go for it.

**Comment by mgr0dzicki** [comment]
Oh so here are the details :). When I was preparing the first tests, the action was still using the bash script to select the baseline. Its logic had a flaw - it was selecting the highest version *strictly* smaller then current and not smaller or equal. This is why the test crate has version `1.2.2`, while the latest published on `crates.io` is `1.2.1`. The problem is - if suddenly version `1.2.2` of official `ref_slice` is published, the baseline for tests changes and they might fail. But now, since we use the logic built in `cargo-semver-checks`, I believe we can safely change the version of the test crate to `1.2.1` and it will be still compared to `1.2.1` published on `crates.io`. This is what the TODO was about.

**Comment by obi1kenobi** [comment]
Awesome, sounds reasonable so let's try it!

**Comment by mgr0dzicki** [comment]
I've already changed the versions in `cargo-semver-action-ref-slice`, the CI passes, so I guess now we can safely remove the TODOs ;)

**Pull request merged**
