### PR TITLE
Add full example for beginers

### PR DESCRIPTION
**Pull request by c-git**
Warning included for using for also publishing as it runs on both pull requests and pushes. Wasn't sure what was the best way to express that they need to not just use it verbatim if they are also going to be publishing using the same workflow

### CODE REVIEW

**Comment by c-git** [comment]
Added where to put the file for beginners

**Comment by obi1kenobi** [comment]
This is definitely nice for beginners, but I think it makes it worse for people who are already comfortable with GitHub Actions because it's more verbose. GitHub Actions usually tend to start by showing the smallest code to run them, then expand into an end-to-end example. For example, consider: https://github.com/actions/setup-python

It's also a bit dangerous because it presents an example workflow that is configured to break on breaking changes, and then runs it on every PR. Many people's workloads are not aligned with this approach, and the example will break for them and be quite frustrating.

I think the basic idea here is sound, and just requires another half hour or hour of polishing work:
- looking at how other GitHub Actions in the ecosystem are documented
- writing a basic workflow that does `cargo publish` and perhaps is triggered on pushed version number tags
- placing that workflow in a new section such that the explanation feels natural and neither overly verbose nor too brisk

**Comment by c-git** [comment]
Ok makes sense, I only push to main when I'm going to release hence that's why it works for me. I haven't found a simple workflow that does cargo publish yet that I can use as an example. I will have to look into triggering on version number tags as well. I also agree about putting it in a new section (I was on the fence about the placement). However, it don't think it's just an hour of work left because of the amount I need to go search for and test. I propose to close this PR for now and reopen once I understand github actions a bit more and have a good example to pattern on. Let me know what you think.

**Comment by obi1kenobi** [comment]
Sounds good to me 👍

**Comment by c-git** [comment]
Ok cool will reopen after I get a better understanding of publishing crates from actions

**Pull request closed without merging**
